spring.application.name=car-auction
spring.data.mongodb.uri=mongodb+srv://riyan:riyan@cluster0.57vmi15.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=carsacution
server.port=8080
jwt.secret=CarAuction2026SuperSecretKeyThatIsAtLeast256BitsLongForHS256Algorithm
jwt.expiration=7200000
auction.duration=5
spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=yyyy-MM-dd'T'HH:mm:ss.SSSXXX

